name: build

# execute this workflow automatically, but only when pushing to main
on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ master ]

jobs:

  linux:
    runs-on: ubuntu-latest
#    container: debian:buster-slim

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Execute script to build linux AppImage
      run: "build/linux/buildAppImage.sh"
      shell: bash

    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: false

    - name: automatic-draft-release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: "${{ steps.tag.outputs.tag }}: [UnderTaker141] by:${{ github.actor }}"
        automatic_release_tag: ${{ steps.tag.outputs.new_tag }}
        files: |
            dist/*.AppImage
